apps/django-tdd/tddtesting/task/urls.py
from . import views
from django.urls import path

app_name = "task"

urlpatterns = [
    path("", views.index, name="list_tasks"),
    path("<int:id>", views.detail, name="task_detail"),
    path("<int:id>/delete", views.delete, name="task_delete"),
]

apps/django-tdd/tddtesting/tddtesting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls"))
]

apps/django-tdd/tddtesting/task/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

apps/django-tdd/tddtesting/task/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseNotAllowed
from django.urls import reverse

from .models import Task


def index(request):
    tasks = Task.objects.all()
    return render(request, "task/index.html", {"tasks": tasks})


def detail(request, id: int):
    try:
        task = Task.objects.get(pk=id)
    except Task.DoesNotExist:
        raise Http404("Task does not exist")
    return render(request, "task/detail.html", {"task": task})


def delete(request, id: int):
    if request.method == "POST":
        try:
            task = Task.objects.get(pk=id)
            task.delete()
        except Task.DoesNotExist:
            raise Http404("Task does not exist")
        return redirect(reverse("task:list_tasks"))
    else:
        return HttpResponseNotAllowed(["POST"])

apps/django-tdd/tddtesting/task/templates/task/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h1>{{task.title}}</h1>
    <p>{{task.description}}</p>
  </body>
</html>

apps/django-tdd/tddtesting/task/templates/task/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    Tasks
    <ul>
      {% for task in tasks %}
      <li>
        <a href="{% url 'task:task_detail' task.id %}">
          {{ task.title }}
        </a>
      {% endfor %}
    </ul>
  </body>
</html>